# Generated by Django 5.2.5 on 2025-08-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_20250822', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionparagraph',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='questionparagraph',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionparagraph',
            name='paragraph_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
