# Generated by Django 5.2.5 on 2025-08-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_20250822', '0002_alter_questionparagraph_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choicecategory',
            name='code',
            field=models.CharField(choices=[('A', 'radio'), ('B', 'check')], max_length=16, unique=True),
        ),
    ]
